### ISSUE TITLE
Submitted input can be deleted

### ISSUE THREAD

**Issue by Favorlock** [beryx/text-io#12]
So I noticed that I create a simple string input reader to get the user's name, after they've submitted the input they can backspace and it'll delete the submitted input.

Welcome, please enter your username:
Evan [Enter]
> // Cursor is now on this line, however, I can backspace back to the beginning of the second line before typing input, yet you can't resubmit input.

Shouldn't submitting input be treated like a new line?

**Comment by siordache** [comment]
On my system, the only TextTerminal that allows moving the caret to a previous line is the SwingTextTerminal. However, it doesn't let you editing text already submitted.

If you give me a few details about your system configuration, I may be able to reproduce your problem.
- What operating system are you using? 
- Which java/jdk version?
- Which type of TextTerminal? 
(If you're not sure, use `System.out.println(textIO.getTextTerminal().getClass());` to display it.)

A code example showing how to reproduce the problem would also be very helpful.
