### ISSUE TITLE
Suggestion logger

### ISSUE THREAD

**Issue by gesteves91** [beryx/text-io#14]
I think it would be awesome to have a function allowing change the logger from debug to any other mode. For example, I would like to change the standard debug mode to something like error or even off.

Thanks,

**Comment by siordache** [comment]
You can configure the logging levels according to the logging library you use.
For example, the [text-io-demo app](https://github.com/beryx/text-io/releases/download/v3.1.4/textio-demo-3.1.4.zip) uses _logback_ and suppresses by default all logging. You can tweak the [logback.xml](https://github.com/beryx/text-io/blob/master/dist/xbin/logback.xml) to display Text-IO logging messages by setting the level of `org.beryx.textio` appropriately (as shown in the [commented section](https://github.com/beryx/text-io/blob/a11d0356badc478de100775ce20c25955c97c345/dist/xbin/logback.xml#L13-L17) of the file).

**Comment by gesteves91** [comment]
Thanks for the suggestion @siordache
