### ISSUE TITLE
how to prevent cursor from moving

### ISSUE THREAD

**Issue by mokun** [beryx/text-io#16]
Hi, 

How do I defensively "fix" the position of the blinking cursor right at the line of the most recent input ?

Currently, the up, down, left, right arrow key can move the cursor key elsewhere on the terminal, which is undesirable, especially that the user may not know that the cursor key needs to be returned to that same spot in order to continue to type the input.

Thanks much for this great API !

**Comment by siordache** [comment]
@mokun I just released the [version 3.2.1](https://search.maven.org/artifact/org.beryx/text-io/3.2.1/jar).

You are still able to move the caret elsewhere on the terminal, but it now jumps to the end of the line of the most recent input when you start typing. This matches the behavior of the console windows provided by IDEs such as Eclipse or IntelliJ.

Does this fix solve your problem?

**Comment by mokun** [comment]
@siordache , 

I just tested it. It works well now. 

Thanks !
