### ISSUE TITLE
prompt input

### ISSUE THREAD

**Issue by mokun** [beryx/text-io#19]
How do I programmatically input something in a prompt ?

Say, I want to run a demo of how to make an input in a prompt.

Is there something in SwingHandler that I can use in order to simulate manually typing in something and hit the enter ?

Thanks !

**Comment by siordache** [comment]
It's not in SwingHandler, but you can use a [Robot-based helper](https://github.com/beryx-gist/text-io-robot/blob/master/src/main/java/org/beryx/textio/robot/RoboTypist.java), as shown in [this demo application](https://github.com/beryx-gist/text-io-robot).

**Comment by mokun** [comment]
RoboTypist class is very great. Thanks!
