### ISSUE TITLE
refresh line

### ISSUE THREAD

**Issue by mokun** [beryx/text-io#21]
Is there a way to go beyond changing the value on the whole screen or the value on, say, the 5th line from the bottom of the screen ?

I can see in the Weather that it calls `terminal.resetLine()` and `terminal.moveToLineStart()` to refresh the value of the very last line on the screen.

In TextTerminal, there is : 

```
    @Override
    public boolean resetLine() {
        return resetToOffset(startLineOffset);
    }

    @Override
    public boolean moveToLineStart() {
        overwriteOffset = startLineOffset;
        return true;
    }
```

We can literally build a game out of the text terminal if we can give the ability to change the value of a text with, say, overwrite(x,y), where x being the x-th position from the left, y being the y-th line from the bottom.

**Comment by siordache** [comment]
No, this is beyond the scope of Text-IO.
You could in principle add this capability to the SwingTextTerminal, but it's not trivial.

**Comment by mokun** [comment]
oh okay. Now I'll be less ambitious :D 

But say, I'd like to refresh a bunch of numbers to the terminal and unfortunately, it needs to occupy 3 lines, instead of just 1 line that your Weather class can do.

Is there any quick way to delete the last 3 lines from the bottom of the screen and then redraw them over ? 

I'm looking at the method ` resetLine()` in `SwingTextTerminal`. It calls up `resetToOffset(startLineOffset)`.

```
    @Override
    public boolean resetLine() {
        return resetToOffset(startLineOffset);
    }

    public boolean resetToOffset(int offset) {
        if(offset < 0) return false;
        display();
        synchronized (editLock) {
            boolean result = true;
            int len = document.getLength() - offset;
            if(len > 0) {
                int oldStartReadLen = startReadLen;
                if(startReadLen > offset) {
                    startReadLen = offset;
                }
                try {
                    document.remove(offset, len);
                } catch (BadLocationException e) {
                    logger.error("Cannot reset to offset " + offset, e);
                    startReadLen = oldStartReadLen;
                    result = false;
                }
                textPane.setCaretPosition(document.getLength());
            }
            return result;
        }
    }

```

**Comment by siordache** [comment]
You need to set a bookmark at the beginning of the block you want to refresh. Then, you call `resetToBookmark` when you want to delete all lines after this bookmark. The Weather application also [uses this technique](https://github.com/beryx/text-io/blob/81c93b2e4567fe50d6744de2be89c6dc345c047b/text-io-demo/src/main/java/org/beryx/textio/demo/app/Weather.java#L62-L67).

**Comment by mokun** [comment]
okay. Closing this.
