### ISSUE TITLE
Question: Add icon in SwingTextTerminal title bar?

### ISSUE THREAD

**Issue by ressec** [beryx/text-io#3]
Hi,

Good job. 
Is it possible to add an icon in the title bar when using the SwingTextTerminal?

**Comment by siordache** [comment]
I added support for configuring the title and icon of the title bar via properties:
- pane.title
- pane.icon.file
- pane.icon.resource
- pane.icon.url

For an example usage see the [UserDataCollector](https://github.com/beryx/text-io/blob/394d648e09571d543fb02542636f1917d71ae649/dist/xbin/UserDataCollector.properties#L28-L31) in the demo application.

**Comment by ressec** [comment]
Hi,


Fantastic, thanks a lot and congrats for this very cool Java terminal.


Regards,

Christophe


Activé 3 juin 2017 à 08:31:15, Serban Iordache (notifications@github.com) a
écrit:

I added support for configuring the title and icon of the title bar via
properties:

   - pane.title
   - pane.icon.file
   - pane.icon.resource
   - pane.icon.url

For an example usage see the UserDataCollector
<https://github.com/beryx/text-io/blob/394d648e09571d543fb02542636f1917d71ae649/dist/xbin/UserDataCollector.properties#L28-L31>
in the demo application.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/beryx/text-io/issues/3#issuecomment-305955450>, or mute
the thread
