### ISSUE TITLE
Input masking doesn't work with SystemTextTerminal

### ISSUE THREAD

**Issue by RedShift1** [beryx/text-io#39]
Sample code:

```java
import org.beryx.textio.TextIO;
import org.beryx.textio.system.SystemTextTerminal;

public class Test
{
    public static void main(String[] args)
    {
        final SystemTextTerminal terminal = new SystemTextTerminal();
        final TextIO             textIO   = new TextIO(terminal);

        final String password = textIO.newStringInputReader()
            .withMinLength(1)
            .withInputMasking(true)
            .read("Password");
    }
}
```

Result:

![textio-input-masking](https://user-images.githubusercontent.com/3098010/161506914-88ec86cf-3d9b-4165-8a7a-a71182aebb5c.gif)

Java version:
```
C:\tmp\textio>java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

Expected result is for the input to be masked and the typed characters to be invisible.

**Comment by siordache** [comment]
Some terminals are not capable of masking the input. [SystemTextTerminal](https://text-io.beryx.org/releases/latest/#_text_terminals) is one of them:
> It is not capable to mask input strings, therefore not recommended when reading sensitive data.

**Comment by RedShift1** [comment]
Ah ok, I missed that in the docs. Thanks.
