### ISSUE TITLE
TextTerminal is a raw type. References to generic type TextTerminal<T> should be parameterized

### ISSUE THREAD

**Issue by tonypiazza** [beryx/text-io#7]
I see a Java compiler warning when declaring a variable of type **TextTerminal**:

> TextTerminal is a raw type. References to generic type TextTerminal<T> should be parameterized

I can get around the issue by declaring the variable like this:

`TextTerminal<?> terminal = textIO.getTextTerminal();`

I'm curious why you chose to make this type generic. In other words, what benefit is there?

Thanks in advance.

-Tony

**Comment by siordache** [comment]
For TextTerminal, the type parameter bound is the type itself: `TextTerminal<T extends TextTerminal<T>>`. 
You may recognize here the same pattern as in [Enum<E extends Enum< E>>](http://www.angelikalanger.com/GenericsFAQ/FAQSections/TypeParameters.html#How%20do%20I%20decrypt%20Enum?).

The benefit is that in the methods `TerminalProperties<T> getProperties()` and `boolean registerUserInterruptHandler(Consumer<T> handler, boolean abortRead)` the compiler may know the actual type of the TextTerminal implementation, which is helpful if you use a specific type of TextTerminal:

```
TextTerminal<?> genericTerminal = TextIoFactory.getTextIO().getTextTerminal();
SwingTextTerminal swingTerminal = new SwingTextTerminal();

// The compiler knows that tt refers to a SwingTextTerminal. No cast is needed in order to call getFrame():
swingTerminal.registerUserInterruptHandler(tt -> tt.getFrame().dispose(), true);

// This will not compile, because getFrame() is not a method of TextTerminal:
// genericTerminal.registerUserInterruptHandler(tt -> tt.getFrame().dispose(), true);

// You have to cast the generic TextTerminal type in order to make the code compile:
genericTerminal.registerUserInterruptHandler(tt -> ((SwingTextTerminal)tt).getFrame().dispose(), true);
```

**Comment by siordache** [comment]
Currently, there are several methods in the Text-IO API that use raw types (for example `public TextTerminal getTextTerminal()` instead of `public TextTerminal<?> getTextTerminal()`) .
I will address this problem in the 3.0 release.
