### ISSUE TITLE
Any way to get TextTerminal.print method to handle \r ?

### ISSUE THREAD

**Issue by tonypiazza** [beryx/text-io#8]
I would like to use the print method of TextTerminal to output a line that is continually updated. In past, I was able to accomplish this using \r at the end of printf format string. So far, I have been unable to get this working with TextIO. Is there any way to accomplish this?

Thanks again,

-Tony

**Comment by tonypiazza** [comment]
It seems I am able to do this when running outside my IDE (Eclipse) and using the rawPrint method. In this case, the type of the actual TextTerminal is JLineTextTerminal. But running inside my IDE, the same code does not work because we get a SwingTextTerminal. Is there any way to support this behavior when using the SwingTextTerminal?

Thanks,

-Tony

**Comment by siordache** [comment]
Currently this is not supported. The javadoc of rawPrint states that the behavior is undefined if the string contains line separators.
I will add support for resetting a line in the next release.

**Comment by siordache** [comment]
I released text-io-3.0.0-alpha-1, which adds support for resetting the current line.
Example usage:
```
TextTerminal<?> textTerm = TextIoFactory.getTextTerminal();
while(true) {
    textTerm.print("" + Math.random());
    try {
	Thread.sleep(1000L);
    } catch (InterruptedException e) {
	e.printStackTrace();
    }
    textTerm.resetLine();
}
```
Please give it a try.

**Comment by tonypiazza** [comment]
I tried using the resetLine feature in 3.0.0-alpha1 but found it caused a
lot of flicker. I recorded 2 videos comparing the difference between using
rawPrintf with \r and resetLine:

Example using rawPrintf with \r
<https://www.dropbox.com/s/9gse785aclk5v72/textio-rawPrintf.mp4?dl=0>

Example using resetLine
<https://www.dropbox.com/s/35enofpujad1fjv/textio-resetLine.mp4?dl=0>

Please let me know if you have any trouble accessing the videos.

Thanks again,

-Tony

**Comment by siordache** [comment]
I can reproduce the flickering if there is a delay between the call to `resetLine`  and the call to `print`.
[This gist](https://gist.github.com/siordache/e0832eb09d7d09cde631f3840575761d) illustrates the problem.

Make sure that in your code there are no operations that may introduce some delay between the call to `resetLine` and the call to `print`.
Instead of:
```
textTerm.resetLine();
textTerm.print(getData());
```
try to use:
```
String infoText = getData();
textTerm.resetLine();
textTerm.print(infoText);
```
Does the flickering disappear?

**Comment by tonypiazza** [comment]
It does not make any difference. My code looks like this:

metrics.addFlight(flight);

terminal.resetLine();

terminal.printf("%,10d\t%,10d\t%,10d\t%,10d",

                metrics.getTotalFlights(),

                metrics.getTotalCancelled(),

                metrics.getTotalDiverted(),

                metrics.getAirports().size()

);


For now I will continue using \r with rawPrintf.

Thanks again for all your help.


-Tony

**Comment by siordache** [comment]
I suspect that the `metrics.getXXX()` methods introduce a small delay.
Try this please:
```
String infoText = String.format("%,10d\t%,10d\t%,10d\t%,10d",
                metrics.getTotalFlights(),
                metrics.getTotalCancelled(),
                metrics.getTotalDiverted(),
                metrics.getAirports().size()
);
textTerm.resetLine();
textTerm.print(infoText);
```
If this still doesn't solve the flickering problem, I will try to come up with another solution in the next release.

**Comment by tonypiazza** [comment]
That didn't make any difference.

Thanks,

-Tony

**Comment by siordache** [comment]
Do you also have flicker with the SwingTextTerminal?

**Comment by tonypiazza** [comment]
It doesn't work at all when using SwingTextTerminal. Only with
JLineTextTerminal.

**Comment by siordache** [comment]
What means it doesn't work at all? Could you please make a video with an example using `resetLine` with SwingTextTerminal?
What operation system do you have?

**Comment by tonypiazza** [comment]
I have attached a video of using resetLine with SwingTextTerminal. As you
can see, the flicker is worse.

Thanks,

-Tony

**Comment by siordache** [comment]
In version 3.0.0-alpha-2 I added the method `moveToLineStart` to TextTerminal. 
Replace `resetLine` with `moveToLineStart` in your program and see how it works.
For JLineTextTerminal, the internal implementation just calls `rawPrint("\r")`, so I expect it to work properly in your application.
However, I am curious how your program behaves with a SwingTextTerminal.

**Comment by tonypiazza** [comment]
Using moveLineToStart gives the same result, which is lots of flicker.

Hope you have a good week ahead.

Thanks,

-Tony

**Comment by siordache** [comment]
Do you have flicker with moveToLineStart even when using the JLineTextTerminal? That's really strange, because, as I said, for JLineTextTerminal I just call `rawPrint("\r")`.

**Comment by tonypiazza** [comment]
There is less flicker when using *moveLineToStart* with *JLineTextTerminal*.

**Comment by siordache** [comment]
Ok, thanks. I think I have a solution to remove the flicker completely for JLineTextTerminal. I will implement it in the next release.

Have a nice week!
Serban

**Comment by siordache** [comment]
@tonypiazza Can you please grab the release 3.0.0-alpha-3 and test again with `moveLineToStart`?
This is the last time I bother you, promise!

I'm interested in the behavior of both JLineTextTerminal and SwingTextTerminal.

Thanks,
Serban

**Comment by tonypiazza** [comment]
Serban,

You are definitely not bothering me! I really appreciate your extra effort
on this feature. I tested it in both JLineTextTerminal and
SwingTextTerminal and it works much better. There is almost no flicker. You
have solved the problem! :-)

Thanks again for all your work on this project.

-Tony

**Comment by siordache** [comment]
Thanks Tony, I'm glad I could help.
